version: '3.7'

services:
  database:
    image: postgres
    container_name: postgresDB
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=databasePG
      - POSTGRES_PASSWORD=testdatabase
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
